-- Local Learning Agent
-- Initial SQLite schema (migration 0001)
-- Additive scope/collection/evidence/activity/PDF grounding schema: migrations/0002_scopes_collections_evidence.sql
-- Timestamp convention: UTC Unix epoch milliseconds (INTEGER)
-- Public/application IDs: UUIDv7 strings generated by application code
-- High-volume source block IDs: INTEGER PRIMARY KEY
--
-- Runtime connection PRAGMAs (apply on every connection; journal_mode once on open):
--   PRAGMA foreign_keys = ON;
--   PRAGMA journal_mode = WAL;
--   PRAGMA synchronous = NORMAL;
--   PRAGMA busy_timeout = 5000;
--   PRAGMA temp_store = MEMORY;
--   PRAGMA trusted_schema = OFF;
--
-- This migration assumes SQLite with JSON1 and FTS5 enabled.

BEGIN IMMEDIATE;

CREATE TABLE schema_migrations (
  version       INTEGER PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  checksum      TEXT NOT NULL,
  applied_at    INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

INSERT INTO schema_migrations (version, name, checksum)
VALUES (1, 'initial_schema', 'REPLACE_WITH_BUILD_TIME_SHA256');

-- -----------------------------------------------------------------------------
-- Application configuration and provider metadata
-- -----------------------------------------------------------------------------

CREATE TABLE app_settings (
  key           TEXT PRIMARY KEY,
  value_json    TEXT NOT NULL CHECK (json_valid(value_json)),
  updated_at    INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT, WITHOUT ROWID;

CREATE TABLE provider_profiles (
  id                    TEXT PRIMARY KEY,
  provider              TEXT NOT NULL CHECK (provider IN ('openai', 'anthropic', 'openrouter')),
  display_name          TEXT NOT NULL,
  base_url              TEXT,
  default_model_id      TEXT,
  secret_ref            TEXT NOT NULL UNIQUE,
  capabilities_json     TEXT NOT NULL DEFAULT '{}'
                            CHECK (json_valid(capabilities_json)),
  enabled               INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  last_verified_at      INTEGER,
  last_verification     TEXT CHECK (last_verification IS NULL OR last_verification IN ('ok', 'failed')),
  last_error_code       TEXT,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

-- API keys are never stored in this table. secret_ref identifies an OS-encrypted
-- secret managed by Electron safeStorage / operating-system credential storage.

CREATE TABLE provider_models (
  provider_profile_id   TEXT NOT NULL REFERENCES provider_profiles(id) ON DELETE CASCADE,
  model_id              TEXT NOT NULL,
  display_name          TEXT,
  capabilities_json     TEXT NOT NULL DEFAULT '{}'
                            CHECK (json_valid(capabilities_json)),
  input_cost_microusd_per_million_tokens   INTEGER,
  output_cost_microusd_per_million_tokens  INTEGER,
  cached_input_cost_microusd_per_million_tokens INTEGER,
  active                INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  discovered_at         INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (provider_profile_id, model_id)
) STRICT, WITHOUT ROWID;

-- -----------------------------------------------------------------------------
-- Learner and Studios
-- -----------------------------------------------------------------------------

CREATE TABLE learner_profile (
  id                    TEXT PRIMARY KEY CHECK (id = 'local-user'),
  display_name          TEXT,
  summary               TEXT,
  background_json       TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(background_json)),
  goals_json            TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(goals_json)),
  preferences_json      TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(preferences_json)),
  onboarding_completed  INTEGER NOT NULL DEFAULT 0 CHECK (onboarding_completed IN (0, 1)),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

INSERT INTO learner_profile (id) VALUES ('local-user');

CREATE TABLE studios (
  id                    TEXT PRIMARY KEY,
  name                  TEXT NOT NULL,
  description           TEXT,
  primary_objective     TEXT,
  preferred_depth       TEXT CHECK (preferred_depth IS NULL OR preferred_depth IN (
                          'overview', 'practical', 'technical', 'research', 'expert'
                        )),
  teaching_style        TEXT NOT NULL DEFAULT 'direct' CHECK (teaching_style IN (
                          'direct', 'socratic', 'paper_companion',
                          'implementation_focused', 'overview_first', 'technical_deep_dive'
                        )),
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                          'active', 'paused', 'completed', 'archived'
                        )),
  sort_order            INTEGER NOT NULL DEFAULT 0,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  archived_at           INTEGER
) STRICT;

CREATE INDEX studios_status_sort_idx ON studios(status, sort_order, updated_at DESC);

CREATE TABLE studio_goals (
  id                    TEXT PRIMARY KEY,
  studio_id             TEXT NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  statement             TEXT NOT NULL,
  priority              INTEGER NOT NULL DEFAULT 0,
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                          'active', 'paused', 'completed', 'abandoned'
                        )),
  is_primary            INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  target_at             INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE UNIQUE INDEX studio_one_active_primary_goal_idx
  ON studio_goals(studio_id)
  WHERE is_primary = 1 AND status = 'active';

CREATE INDEX studio_goals_status_idx ON studio_goals(studio_id, status, priority DESC);

-- -----------------------------------------------------------------------------
-- Content-addressed assets, sources, and source versions
-- -----------------------------------------------------------------------------

CREATE TABLE assets (
  sha256                TEXT PRIMARY KEY CHECK (length(sha256) = 64),
  media_type            TEXT NOT NULL,
  byte_size             INTEGER NOT NULL CHECK (byte_size >= 0),
  relative_path         TEXT NOT NULL UNIQUE,
  original_filename     TEXT,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  last_verified_at      INTEGER
) STRICT, WITHOUT ROWID;

CREATE TABLE sources (
  id                    TEXT PRIMARY KEY,
  kind                  TEXT NOT NULL CHECK (kind IN (
                          'pdf', 'web', 'markdown', 'text', 'transcript',
                          'audio', 'video', 'note', 'repository', 'other'
                        )),
  title                 TEXT NOT NULL,
  subtitle              TEXT,
  author                TEXT,
  publisher             TEXT,
  canonical_url         TEXT,
  original_url          TEXT,
  language              TEXT,
  published_at          INTEGER,
  lifecycle_status      TEXT NOT NULL DEFAULT 'inbox' CHECK (lifecycle_status IN (
                          'inbox', 'active', 'archived', 'deleted'
                        )),
  processing_status     TEXT NOT NULL DEFAULT 'queued' CHECK (processing_status IN (
                          'queued', 'acquiring', 'extracting', 'quality_check',
                          'normalizing', 'structuring', 'blocking',
                          'indexing_lexical', 'embedding', 'ready',
                          'needs_attention', 'failed', 'cancelled'
                        )),
  processing_error_code TEXT,
  processing_error      TEXT,
  metadata_json         TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata_json)),
  captured_at           INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  deleted_at            INTEGER
) STRICT;

CREATE UNIQUE INDEX sources_canonical_url_live_idx
  ON sources(canonical_url)
  WHERE canonical_url IS NOT NULL AND lifecycle_status <> 'deleted';

CREATE INDEX sources_inbox_idx
  ON sources(lifecycle_status, processing_status, created_at DESC);
CREATE INDEX sources_kind_idx ON sources(kind, updated_at DESC);
CREATE INDEX sources_published_idx ON sources(published_at DESC) WHERE published_at IS NOT NULL;

CREATE TABLE source_versions (
  id                    TEXT PRIMARY KEY,
  source_id             TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  version_number        INTEGER NOT NULL CHECK (version_number >= 1),
  status                TEXT NOT NULL DEFAULT 'processing' CHECK (status IN (
                          'processing', 'ready', 'needs_attention', 'failed', 'superseded'
                        )),
  asset_hash            TEXT REFERENCES assets(sha256) ON DELETE RESTRICT,
  normalized_hash       TEXT CHECK (normalized_hash IS NULL OR length(normalized_hash) = 64),
  mime_type             TEXT,
  normalized_path       TEXT,
  parser_id             TEXT NOT NULL,
  parser_version        TEXT NOT NULL,
  structure_schema_version INTEGER NOT NULL DEFAULT 1 CHECK (structure_schema_version >= 1),
  block_schema_version  INTEGER NOT NULL DEFAULT 1 CHECK (block_schema_version >= 1),
  page_count            INTEGER CHECK (page_count IS NULL OR page_count >= 0),
  duration_ms           INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
  word_count            INTEGER CHECK (word_count IS NULL OR word_count >= 0),
  extraction_quality    REAL CHECK (extraction_quality IS NULL OR
                                    (extraction_quality >= 0.0 AND extraction_quality <= 1.0)),
  quality_details_json  TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(quality_details_json)),
  acquired_at           INTEGER,
  ready_at              INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (source_id, version_number),
  UNIQUE (source_id, normalized_hash)
) STRICT;

CREATE INDEX source_versions_source_idx ON source_versions(source_id, version_number DESC);
CREATE INDEX source_versions_status_idx ON source_versions(status, created_at DESC);
CREATE INDEX source_versions_hash_idx ON source_versions(normalized_hash);

CREATE TRIGGER source_version_ready_requires_hash_insert
BEFORE INSERT ON source_versions
FOR EACH ROW
WHEN NEW.status = 'ready' AND NEW.normalized_hash IS NULL
BEGIN
  SELECT RAISE(ABORT, 'ready source version requires normalized_hash');
END;

CREATE TRIGGER source_version_ready_requires_hash_update
BEFORE UPDATE OF status, normalized_hash ON source_versions
FOR EACH ROW
WHEN NEW.status = 'ready' AND NEW.normalized_hash IS NULL
BEGIN
  SELECT RAISE(ABORT, 'ready source version requires normalized_hash');
END;

CREATE TABLE source_active_versions (
  source_id             TEXT PRIMARY KEY REFERENCES sources(id) ON DELETE CASCADE,
  source_version_id     TEXT NOT NULL UNIQUE REFERENCES source_versions(id) ON DELETE CASCADE,
  selected_at           INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT, WITHOUT ROWID;

CREATE TRIGGER source_active_version_same_source_insert
BEFORE INSERT ON source_active_versions
FOR EACH ROW
WHEN (SELECT source_id FROM source_versions WHERE id = NEW.source_version_id) IS NOT NEW.source_id
  OR (SELECT status FROM source_versions WHERE id = NEW.source_version_id) NOT IN ('ready', 'needs_attention')
BEGIN
  SELECT RAISE(ABORT, 'active source version must belong to source and be usable');
END;

CREATE TRIGGER source_active_version_same_source_update
BEFORE UPDATE ON source_active_versions
FOR EACH ROW
WHEN (SELECT source_id FROM source_versions WHERE id = NEW.source_version_id) IS NOT NEW.source_id
  OR (SELECT status FROM source_versions WHERE id = NEW.source_version_id) NOT IN ('ready', 'needs_attention')
BEGIN
  SELECT RAISE(ABORT, 'active source version must belong to source and be usable');
END;

CREATE TABLE studio_sources (
  studio_id             TEXT NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  source_id             TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  role                  TEXT NOT NULL DEFAULT 'reference' CHECK (role IN (
                          'foundation', 'current_frontier', 'explanation',
                          'implementation', 'criticism', 'reference',
                          'exercise', 'user_note'
                        )),
  position              INTEGER NOT NULL DEFAULT 0,
  pinned                INTEGER NOT NULL DEFAULT 0 CHECK (pinned IN (0, 1)),
  added_reason          TEXT,
  added_at              INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (studio_id, source_id)
) STRICT, WITHOUT ROWID;

CREATE INDEX studio_sources_role_idx ON studio_sources(studio_id, role, position);

CREATE TABLE source_provenance (
  id                    TEXT PRIMARY KEY,
  source_id             TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  provenance_type       TEXT NOT NULL CHECK (provenance_type IN (
                          'file_import', 'paste', 'browser_capture', 'direct_fetch',
                          'web_search', 'podcast_rss', 'transcription',
                          'user_note', 'derived', 'studio_import'
                        )),
  originating_url       TEXT,
  referring_source_id   TEXT REFERENCES sources(id) ON DELETE SET NULL,
  tool_run_id           TEXT REFERENCES tool_runs(id) ON DELETE SET NULL,
  metadata_json         TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata_json)),
  captured_at           INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX source_provenance_source_idx ON source_provenance(source_id, captured_at DESC);

CREATE TABLE source_relations (
  from_source_id        TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  to_source_id          TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  relation              TEXT NOT NULL CHECK (relation IN (
                          'references', 'builds_on', 'explains', 'implements',
                          'criticizes', 'contradicts', 'duplicates', 'version_of',
                          'transcript_of', 'related'
                        )),
  confidence            REAL CHECK (confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)),
  evidence_json         TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(evidence_json)),
  created_by            TEXT NOT NULL CHECK (created_by IN ('user', 'model', 'import', 'system')),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (from_source_id, to_source_id, relation),
  CHECK (from_source_id <> to_source_id)
) STRICT, WITHOUT ROWID;

-- -----------------------------------------------------------------------------
-- Ingestion stages, derived artifacts, and canonical source blocks
-- -----------------------------------------------------------------------------

CREATE TABLE ingestion_stage_runs (
  id                    TEXT PRIMARY KEY,
  source_version_id     TEXT NOT NULL REFERENCES source_versions(id) ON DELETE CASCADE,
  stage                 TEXT NOT NULL CHECK (stage IN (
                          'acquire', 'extract', 'quality_check', 'normalize',
                          'structure', 'block', 'index_lexical', 'embed'
                        )),
  stage_version         TEXT NOT NULL,
  status                TEXT NOT NULL CHECK (status IN (
                          'queued', 'running', 'succeeded', 'failed', 'cancelled'
                        )),
  attempt               INTEGER NOT NULL DEFAULT 1 CHECK (attempt >= 1),
  input_hash            TEXT,
  output_hash           TEXT,
  job_id                TEXT REFERENCES jobs(id) ON DELETE SET NULL,
  worker_id             TEXT,
  progress              REAL NOT NULL DEFAULT 0.0 CHECK (progress >= 0.0 AND progress <= 1.0),
  error_code            TEXT,
  error_message         TEXT,
  started_at            INTEGER,
  completed_at          INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (source_version_id, stage, stage_version, attempt)
) STRICT;

CREATE INDEX ingestion_stage_status_idx ON ingestion_stage_runs(status, created_at);
CREATE INDEX ingestion_stage_source_idx ON ingestion_stage_runs(source_version_id, stage, attempt DESC);

CREATE TABLE derived_artifacts (
  id                    TEXT PRIMARY KEY,
  source_version_id     TEXT NOT NULL REFERENCES source_versions(id) ON DELETE CASCADE,
  kind                  TEXT NOT NULL CHECK (kind IN (
                          'normalized_markdown', 'structured_document', 'page_image',
                          'transcript', 'outline', 'vision_extraction', 'thumbnail',
                          'other'
                        )),
  relative_path         TEXT NOT NULL,
  content_hash          TEXT NOT NULL CHECK (length(content_hash) = 64),
  media_type            TEXT NOT NULL,
  byte_size             INTEGER NOT NULL CHECK (byte_size >= 0),
  producer_id           TEXT NOT NULL,
  producer_version      TEXT NOT NULL,
  metadata_json         TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata_json)),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (source_version_id, kind, content_hash)
) STRICT;

CREATE INDEX derived_artifacts_source_idx ON derived_artifacts(source_version_id, kind);

CREATE TABLE source_blocks (
  id                    INTEGER PRIMARY KEY,
  public_id             TEXT NOT NULL UNIQUE,
  source_version_id     TEXT NOT NULL REFERENCES source_versions(id) ON DELETE CASCADE,
  ordinal               INTEGER NOT NULL CHECK (ordinal >= 0),
  kind                  TEXT NOT NULL CHECK (kind IN (
                          'heading', 'paragraph', 'list', 'code', 'equation',
                          'table', 'caption', 'quote', 'transcript', 'note'
                        )),
  text                  TEXT NOT NULL,
  heading_path_json     TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(heading_path_json)),
  heading_path_text     TEXT NOT NULL DEFAULT '',
  page_start            INTEGER CHECK (page_start IS NULL OR page_start >= 1),
  page_end              INTEGER CHECK (page_end IS NULL OR page_end >= page_start),
  time_start_ms         INTEGER CHECK (time_start_ms IS NULL OR time_start_ms >= 0),
  time_end_ms           INTEGER CHECK (time_end_ms IS NULL OR time_end_ms >= time_start_ms),
  char_start            INTEGER CHECK (char_start IS NULL OR char_start >= 0),
  char_end              INTEGER CHECK (char_end IS NULL OR char_end >= char_start),
  locator_json          TEXT NOT NULL CHECK (json_valid(locator_json)),
  content_hash          TEXT NOT NULL CHECK (length(content_hash) = 64),
  token_estimate        INTEGER NOT NULL CHECK (token_estimate >= 0),
  block_schema_version  INTEGER NOT NULL DEFAULT 1 CHECK (block_schema_version >= 1),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (source_version_id, ordinal)
) STRICT;

CREATE INDEX source_blocks_version_idx ON source_blocks(source_version_id, ordinal);
CREATE INDEX source_blocks_hash_idx ON source_blocks(content_hash);
CREATE INDEX source_blocks_page_idx ON source_blocks(source_version_id, page_start, page_end);
CREATE INDEX source_blocks_time_idx ON source_blocks(source_version_id, time_start_ms, time_end_ms);

CREATE VIRTUAL TABLE source_blocks_fts USING fts5(
  source_version_id UNINDEXED,
  kind UNINDEXED,
  heading_path_text,
  text,
  content = 'source_blocks',
  content_rowid = 'id',
  tokenize = 'unicode61 remove_diacritics 2'
);

CREATE TRIGGER source_blocks_fts_insert
AFTER INSERT ON source_blocks
BEGIN
  INSERT INTO source_blocks_fts(rowid, source_version_id, kind, heading_path_text, text)
  VALUES (NEW.id, NEW.source_version_id, NEW.kind, NEW.heading_path_text, NEW.text);
END;

CREATE TRIGGER source_blocks_fts_delete
AFTER DELETE ON source_blocks
BEGIN
  INSERT INTO source_blocks_fts(source_blocks_fts, rowid, source_version_id, kind, heading_path_text, text)
  VALUES ('delete', OLD.id, OLD.source_version_id, OLD.kind, OLD.heading_path_text, OLD.text);
END;

CREATE TRIGGER source_blocks_fts_update
AFTER UPDATE ON source_blocks
BEGIN
  INSERT INTO source_blocks_fts(source_blocks_fts, rowid, source_version_id, kind, heading_path_text, text)
  VALUES ('delete', OLD.id, OLD.source_version_id, OLD.kind, OLD.heading_path_text, OLD.text);
  INSERT INTO source_blocks_fts(rowid, source_version_id, kind, heading_path_text, text)
  VALUES (NEW.id, NEW.source_version_id, NEW.kind, NEW.heading_path_text, NEW.text);
END;

CREATE TABLE embeddings (
  id                    INTEGER PRIMARY KEY,
  source_block_id       INTEGER NOT NULL REFERENCES source_blocks(id) ON DELETE CASCADE,
  model_id              TEXT NOT NULL,
  model_revision        TEXT NOT NULL,
  dimensions            INTEGER NOT NULL CHECK (dimensions > 0),
  normalized            INTEGER NOT NULL DEFAULT 1 CHECK (normalized IN (0, 1)),
  vector                BLOB NOT NULL,
  input_hash            TEXT NOT NULL CHECK (length(input_hash) = 64),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (source_block_id, model_id, model_revision),
  CHECK (length(vector) = dimensions * 4)
) STRICT;

CREATE INDEX embeddings_model_idx ON embeddings(model_id, model_revision, dimensions);
CREATE INDEX embeddings_block_idx ON embeddings(source_block_id);

CREATE TABLE source_cards (
  id                    TEXT PRIMARY KEY,
  source_version_id     TEXT NOT NULL REFERENCES source_versions(id) ON DELETE CASCADE,
  provider_profile_id   TEXT REFERENCES provider_profiles(id) ON DELETE SET NULL,
  model_id              TEXT NOT NULL,
  prompt_version        TEXT NOT NULL,
  schema_version        INTEGER NOT NULL CHECK (schema_version >= 1),
  input_hash            TEXT NOT NULL CHECK (length(input_hash) = 64),
  status                TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('ready', 'stale', 'failed')),
  card_json             TEXT NOT NULL CHECK (json_valid(card_json)),
  card_markdown         TEXT,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (source_version_id, model_id, prompt_version, schema_version, input_hash)
) STRICT;

CREATE INDEX source_cards_source_idx ON source_cards(source_version_id, created_at DESC);

CREATE TABLE annotations (
  id                    TEXT PRIMARY KEY,
  source_id             TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  source_version_id     TEXT REFERENCES source_versions(id) ON DELETE SET NULL,
  source_block_id       INTEGER REFERENCES source_blocks(id) ON DELETE SET NULL,
  kind                  TEXT NOT NULL CHECK (kind IN ('highlight', 'note', 'question', 'bookmark')),
  selected_text         TEXT,
  body                  TEXT,
  locator_json          TEXT CHECK (locator_json IS NULL OR json_valid(locator_json)),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX annotations_source_idx ON annotations(source_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- Concepts and Studio curriculum state
-- -----------------------------------------------------------------------------

CREATE TABLE concepts (
  id                    TEXT PRIMARY KEY,
  canonical_name        TEXT NOT NULL,
  normalized_name       TEXT NOT NULL UNIQUE,
  description           TEXT,
  domain                TEXT,
  created_by            TEXT NOT NULL CHECK (created_by IN ('user', 'model', 'import', 'system')),
  creation_source_id    TEXT REFERENCES sources(id) ON DELETE SET NULL,
  merged_into_id        TEXT REFERENCES concepts(id) ON DELETE SET NULL,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  CHECK (merged_into_id IS NULL OR merged_into_id <> id)
) STRICT;

CREATE INDEX concepts_domain_idx ON concepts(domain, canonical_name);

CREATE TABLE concept_aliases (
  normalized_alias      TEXT PRIMARY KEY,
  alias                 TEXT NOT NULL,
  concept_id            TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  language              TEXT,
  created_by            TEXT NOT NULL CHECK (created_by IN ('user', 'model', 'import', 'system')),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT, WITHOUT ROWID;

CREATE INDEX concept_aliases_concept_idx ON concept_aliases(concept_id);

CREATE TABLE concept_relations (
  from_concept_id       TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  to_concept_id         TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  relation              TEXT NOT NULL CHECK (relation IN (
                          'parent', 'prerequisite', 'related', 'contrasts_with',
                          'part_of', 'builds_on'
                        )),
  confidence            REAL CHECK (confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)),
  created_by            TEXT NOT NULL CHECK (created_by IN ('user', 'model', 'import', 'system')),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (from_concept_id, to_concept_id, relation),
  CHECK (from_concept_id <> to_concept_id)
) STRICT, WITHOUT ROWID;

CREATE TABLE studio_concepts (
  studio_id             TEXT NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  concept_id            TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  importance            INTEGER NOT NULL DEFAULT 0,
  sequence              INTEGER,
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                          'active', 'prerequisite', 'deferred', 'completed', 'removed'
                        )),
  notes                 TEXT,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (studio_id, concept_id)
) STRICT, WITHOUT ROWID;

CREATE INDEX studio_concepts_sequence_idx ON studio_concepts(studio_id, sequence, importance DESC);

-- -----------------------------------------------------------------------------
-- Agent sessions, messages, tools, and citations
-- -----------------------------------------------------------------------------

CREATE TABLE sessions (
  id                    TEXT PRIMARY KEY,
  studio_id             TEXT REFERENCES studios(id) ON DELETE SET NULL,
  mode                  TEXT NOT NULL CHECK (mode IN (
                          'onboarding', 'learn', 'research', 'probe', 'triage'
                        )),
  title                 TEXT,
  objective             TEXT,
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                          'active', 'completed', 'cancelled', 'failed'
                        )),
  provider_profile_id   TEXT REFERENCES provider_profiles(id) ON DELETE SET NULL,
  model_id              TEXT,
  prompt_version        TEXT,
  runtime_context_json  TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(runtime_context_json)),
  summary               TEXT,
  started_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  ended_at              INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX sessions_studio_idx ON sessions(studio_id, started_at DESC);
CREATE INDEX sessions_status_idx ON sessions(status, updated_at DESC);

CREATE TABLE session_sources (
  session_id            TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  source_id             TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  source_version_id     TEXT REFERENCES source_versions(id) ON DELETE SET NULL,
  role                  TEXT NOT NULL DEFAULT 'context' CHECK (role IN (
                          'active', 'selected', 'context', 'comparison', 'research_evidence'
                        )),
  added_at              INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (session_id, source_id, role)
) STRICT, WITHOUT ROWID;

CREATE TABLE messages (
  id                    TEXT PRIMARY KEY,
  session_id            TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  ordinal               INTEGER NOT NULL CHECK (ordinal >= 0),
  role                  TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
  content_text          TEXT,
  content_json          TEXT CHECK (content_json IS NULL OR json_valid(content_json)),
  provider_message_id   TEXT,
  status                TEXT NOT NULL DEFAULT 'complete' CHECK (status IN (
                          'streaming', 'complete', 'cancelled', 'failed'
                        )),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (session_id, ordinal),
  CHECK (content_text IS NOT NULL OR content_json IS NOT NULL)
) STRICT;

CREATE INDEX messages_session_idx ON messages(session_id, ordinal);

CREATE TABLE tool_runs (
  id                    TEXT PRIMARY KEY,
  session_id            TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  message_id            TEXT REFERENCES messages(id) ON DELETE SET NULL,
  provider_tool_call_id TEXT,
  tool_name             TEXT NOT NULL,
  input_json            TEXT NOT NULL CHECK (json_valid(input_json)),
  output_json           TEXT CHECK (output_json IS NULL OR json_valid(output_json)),
  status                TEXT NOT NULL CHECK (status IN (
                          'requested', 'approved', 'running', 'succeeded',
                          'failed', 'cancelled', 'denied'
                        )),
  approval_required     INTEGER NOT NULL DEFAULT 0 CHECK (approval_required IN (0, 1)),
  approved_at           INTEGER,
  error_code            TEXT,
  error_message         TEXT,
  started_at            INTEGER,
  completed_at          INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX tool_runs_session_idx ON tool_runs(session_id, created_at);
CREATE INDEX tool_runs_status_idx ON tool_runs(status, created_at);

CREATE TABLE citations (
  id                    TEXT PRIMARY KEY,
  message_id            TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  handle                TEXT NOT NULL,
  occurrence_index      INTEGER NOT NULL DEFAULT 0 CHECK (occurrence_index >= 0),
  source_block_id       INTEGER NOT NULL REFERENCES source_blocks(id) ON DELETE RESTRICT,
  response_char_start   INTEGER CHECK (response_char_start IS NULL OR response_char_start >= 0),
  response_char_end     INTEGER CHECK (response_char_end IS NULL OR response_char_end >= response_char_start),
  supporting_quote      TEXT,
  locator_snapshot_json TEXT NOT NULL CHECK (json_valid(locator_snapshot_json)),
  verification_status   TEXT NOT NULL CHECK (verification_status IN (
                          'verified', 'invalid_handle', 'missing_block',
                          'locator_failed', 'repaired', 'removed'
                        )),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (message_id, handle, occurrence_index)
) STRICT;

CREATE INDEX citations_message_idx ON citations(message_id, occurrence_index);
CREATE INDEX citations_block_idx ON citations(source_block_id);

-- -----------------------------------------------------------------------------
-- Probe and evidence-backed learner state
-- -----------------------------------------------------------------------------

CREATE TABLE probes (
  id                    TEXT PRIMARY KEY,
  session_id            TEXT NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE,
  studio_id             TEXT NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  source_version_id     TEXT REFERENCES source_versions(id) ON DELETE SET NULL,
  objective             TEXT NOT NULL,
  desired_depth         TEXT NOT NULL DEFAULT 'explain' CHECK (desired_depth IN (
                          'explain', 'apply', 'compare_or_critique'
                        )),
  max_turns             INTEGER NOT NULL DEFAULT 5 CHECK (max_turns BETWEEN 1 AND 12),
  status                TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
                          'draft', 'selecting_objective', 'building_rubric',
                          'asking', 'awaiting_answer', 'evaluating',
                          'completed', 'user_stopped', 'failed'
                        )),
  stop_reason           TEXT CHECK (stop_reason IS NULL OR stop_reason IN (
                          'objective_met', 'prerequisite_gap', 'teach_before_continue',
                          'turn_limit', 'user_stopped', 'failed'
                        )),
  result_json           TEXT CHECK (result_json IS NULL OR json_valid(result_json)),
  started_at            INTEGER,
  completed_at          INTEGER,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE TABLE probe_concepts (
  probe_id              TEXT NOT NULL REFERENCES probes(id) ON DELETE CASCADE,
  concept_id            TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  purpose               TEXT,
  priority              INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (probe_id, concept_id)
) STRICT, WITHOUT ROWID;

CREATE TABLE probe_turns (
  id                    TEXT PRIMARY KEY,
  probe_id              TEXT NOT NULL REFERENCES probes(id) ON DELETE CASCADE,
  turn_number           INTEGER NOT NULL CHECK (turn_number >= 1),
  question_message_id   TEXT NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  answer_message_id     TEXT REFERENCES messages(id) ON DELETE RESTRICT,
  feedback_message_id   TEXT REFERENCES messages(id) ON DELETE RESTRICT,
  question_type         TEXT NOT NULL CHECK (question_type IN (
                          'explain', 'distinguish', 'predict', 'apply',
                          'diagnose', 'design', 'compare', 'critique', 'connect'
                        )),
  purpose               TEXT NOT NULL,
  rubric_json           TEXT NOT NULL CHECK (json_valid(rubric_json)),
  evaluation_json       TEXT CHECK (evaluation_json IS NULL OR json_valid(evaluation_json)),
  status                TEXT NOT NULL DEFAULT 'awaiting_answer' CHECK (status IN (
                          'awaiting_answer', 'evaluating', 'completed', 'failed', 'cancelled'
                        )),
  asked_at              INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  answered_at           INTEGER,
  evaluated_at          INTEGER,
  UNIQUE (probe_id, turn_number)
) STRICT;

CREATE INDEX probe_turns_probe_idx ON probe_turns(probe_id, turn_number);

-- Immutable append-only evidence ledger. Retraction/correction is represented by
-- a new event that references the earlier event through retracts_event_id.
CREATE TABLE learning_events (
  id                    TEXT PRIMARY KEY,
  studio_id             TEXT REFERENCES studios(id) ON DELETE SET NULL,
  concept_id            TEXT NOT NULL REFERENCES concepts(id) ON DELETE RESTRICT,
  session_id            TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  probe_turn_id         TEXT REFERENCES probe_turns(id) ON DELETE SET NULL,
  source_block_id       INTEGER REFERENCES source_blocks(id) ON DELETE SET NULL,
  event_kind            TEXT NOT NULL CHECK (event_kind IN (
                          'encountered', 'explanation_evidence', 'application_evidence',
                          'critique_evidence', 'misconception_hypothesis',
                          'misconception_confirmed', 'correction', 'review_success',
                          'review_failure', 'manual_assertion', 'manual_correction',
                          'retraction'
                        )),
  demonstrated_level    TEXT CHECK (demonstrated_level IS NULL OR demonstrated_level IN (
                          'encountered', 'can_explain', 'can_apply',
                          'can_compare_or_critique'
                        )),
  confidence            REAL NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
  evidence_message_id   TEXT REFERENCES messages(id) ON DELETE SET NULL,
  evidence_excerpt      TEXT,
  question_text         TEXT,
  rationale             TEXT NOT NULL,
  rubric_json           TEXT CHECK (rubric_json IS NULL OR json_valid(rubric_json)),
  evaluator_provider    TEXT,
  evaluator_model       TEXT,
  evaluator_prompt_version TEXT,
  context_json          TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(context_json)),
  retracts_event_id     TEXT REFERENCES learning_events(id) ON DELETE RESTRICT,
  event_hash            TEXT NOT NULL UNIQUE CHECK (length(event_hash) = 64),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  CHECK (
    (event_kind = 'retraction' AND retracts_event_id IS NOT NULL) OR
    (event_kind <> 'retraction' AND retracts_event_id IS NULL)
  ),
  CHECK (
    demonstrated_level IS NULL OR
    event_kind IN (
      'encountered', 'explanation_evidence', 'application_evidence',
      'critique_evidence', 'review_success', 'manual_assertion', 'manual_correction'
    )
  )
) STRICT;

CREATE INDEX learning_events_concept_idx ON learning_events(concept_id, created_at DESC);
CREATE INDEX learning_events_studio_idx ON learning_events(studio_id, concept_id, created_at DESC);
CREATE INDEX learning_events_probe_idx ON learning_events(probe_turn_id);
CREATE INDEX learning_events_retraction_idx ON learning_events(retracts_event_id)
  WHERE retracts_event_id IS NOT NULL;

CREATE TRIGGER learning_events_no_update
BEFORE UPDATE ON learning_events
BEGIN
  SELECT RAISE(ABORT, 'learning_events is append-only');
END;

CREATE TRIGGER learning_events_no_delete
BEFORE DELETE ON learning_events
BEGIN
  SELECT RAISE(ABORT, 'learning_events is append-only');
END;

CREATE TABLE concept_state (
  scope_key             TEXT NOT NULL,
  scope_type            TEXT NOT NULL CHECK (scope_type IN ('global', 'studio')),
  studio_id             TEXT REFERENCES studios(id) ON DELETE CASCADE,
  concept_id            TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  mastery_level         TEXT NOT NULL DEFAULT 'unassessed' CHECK (mastery_level IN (
                          'unassessed', 'encountered', 'can_explain',
                          'can_apply', 'can_compare_or_critique'
                        )),
  confidence            REAL NOT NULL DEFAULT 0.0 CHECK (confidence >= 0.0 AND confidence <= 1.0),
  certainty_status      TEXT NOT NULL DEFAULT 'uncertain' CHECK (certainty_status IN (
                          'unassessed', 'secure', 'uncertain', 'contradicted', 'retired'
                        )),
  evidence_count        INTEGER NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  contradictory_count  INTEGER NOT NULL DEFAULT 0 CHECK (contradictory_count >= 0),
  strongest_event_id    TEXT REFERENCES learning_events(id) ON DELETE SET NULL,
  last_demonstrated_at  INTEGER,
  next_review_at        INTEGER,
  contexts_json         TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(contexts_json)),
  projection_version    INTEGER NOT NULL DEFAULT 1 CHECK (projection_version >= 1),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  PRIMARY KEY (scope_key, concept_id),
  CHECK (
    (scope_type = 'global' AND studio_id IS NULL AND scope_key = 'global') OR
    (scope_type = 'studio' AND studio_id IS NOT NULL AND scope_key = studio_id)
  )
) STRICT, WITHOUT ROWID;

CREATE INDEX concept_state_review_idx ON concept_state(next_review_at)
  WHERE next_review_at IS NOT NULL AND certainty_status <> 'retired';
CREATE INDEX concept_state_studio_idx ON concept_state(studio_id, mastery_level, confidence DESC);

CREATE TABLE learner_memories (
  id                    TEXT PRIMARY KEY,
  scope_type            TEXT NOT NULL CHECK (scope_type IN ('global', 'studio')),
  studio_id             TEXT REFERENCES studios(id) ON DELETE CASCADE,
  kind                  TEXT NOT NULL CHECK (kind IN (
                          'background', 'goal', 'preference', 'project', 'constraint',
                          'strategy', 'other'
                        )),
  statement             TEXT NOT NULL,
  confidence            REAL NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
  evidence_event_id     TEXT REFERENCES learning_events(id) ON DELETE SET NULL,
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                          'proposed', 'active', 'corrected', 'retracted'
                        )),
  created_by            TEXT NOT NULL CHECK (created_by IN ('user', 'model', 'import', 'system')),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  CHECK (
    (scope_type = 'global' AND studio_id IS NULL) OR
    (scope_type = 'studio' AND studio_id IS NOT NULL)
  )
) STRICT;

CREATE INDEX learner_memories_scope_idx ON learner_memories(scope_type, studio_id, status, updated_at DESC);

CREATE TABLE review_queue (
  id                    TEXT PRIMARY KEY,
  scope_key             TEXT NOT NULL,
  scope_type            TEXT NOT NULL CHECK (scope_type IN ('global', 'studio')),
  concept_id            TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  studio_id             TEXT REFERENCES studios(id) ON DELETE CASCADE,
  due_at                INTEGER NOT NULL,
  priority              INTEGER NOT NULL DEFAULT 0,
  reason                TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN (
                          'scheduled', 'started', 'completed', 'dismissed', 'superseded'
                        )),
  completed_event_id    TEXT REFERENCES learning_events(id) ON DELETE SET NULL,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (scope_key, concept_id, due_at),
  CHECK (
    (scope_type = 'global' AND studio_id IS NULL AND scope_key = 'global') OR
    (scope_type = 'studio' AND studio_id IS NOT NULL AND scope_key = studio_id)
  )
) STRICT;

CREATE INDEX review_queue_due_idx ON review_queue(status, due_at, priority DESC);

-- At most one primary next action is active per Studio. Today may also hold global
-- actions with studio_id NULL.
CREATE TABLE next_actions (
  id                    TEXT PRIMARY KEY,
  studio_id             TEXT REFERENCES studios(id) ON DELETE CASCADE,
  action_type           TEXT NOT NULL CHECK (action_type IN (
                          'read_source_section', 'complete_probe', 'answer_application',
                          'compare_sources', 'revisit_prerequisite', 'conduct_research',
                          'add_source', 'review_concept'
                        )),
  source_id             TEXT REFERENCES sources(id) ON DELETE SET NULL,
  source_block_id       INTEGER REFERENCES source_blocks(id) ON DELETE SET NULL,
  concept_id            TEXT REFERENCES concepts(id) ON DELETE SET NULL,
  title                 TEXT NOT NULL,
  rationale             TEXT NOT NULL,
  payload_json          TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload_json)),
  priority              INTEGER NOT NULL DEFAULT 0,
  is_primary            INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                          'active', 'completed', 'dismissed', 'superseded'
                        )),
  due_at                INTEGER,
  created_by            TEXT NOT NULL CHECK (created_by IN ('user', 'model', 'system')),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE UNIQUE INDEX next_actions_one_primary_per_studio_idx
  ON next_actions(studio_id)
  WHERE studio_id IS NOT NULL AND is_primary = 1 AND status = 'active';
CREATE INDEX next_actions_today_idx ON next_actions(status, priority DESC, due_at, created_at DESC);

-- -----------------------------------------------------------------------------
-- Persistent work queue, extension capture, usage, and budgets
-- -----------------------------------------------------------------------------

CREATE TABLE jobs (
  id                    TEXT PRIMARY KEY,
  type                  TEXT NOT NULL,
  payload_json          TEXT NOT NULL CHECK (json_valid(payload_json)),
  result_json           TEXT CHECK (result_json IS NULL OR json_valid(result_json)),
  status                TEXT NOT NULL DEFAULT 'queued' CHECK (status IN (
                          'queued', 'running', 'succeeded', 'failed', 'cancelled'
                        )),
  priority              INTEGER NOT NULL DEFAULT 0,
  progress              REAL NOT NULL DEFAULT 0.0 CHECK (progress >= 0.0 AND progress <= 1.0),
  attempts              INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts          INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts >= 1),
  dedupe_key            TEXT,
  worker_id             TEXT,
  locked_at             INTEGER,
  available_at          INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  started_at            INTEGER,
  completed_at          INTEGER,
  error_code            TEXT,
  error_message         TEXT,
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX jobs_claim_idx ON jobs(status, available_at, priority DESC, created_at);
CREATE UNIQUE INDEX jobs_active_dedupe_idx ON jobs(dedupe_key)
  WHERE dedupe_key IS NOT NULL AND status IN ('queued', 'running');

CREATE TABLE capture_requests (
  id                    TEXT PRIMARY KEY,
  external_request_id   TEXT NOT NULL,
  extension_id          TEXT NOT NULL,
  browser               TEXT NOT NULL CHECK (browser IN ('chrome', 'edge', 'firefox', 'safari', 'unknown')),
  payload_json          TEXT NOT NULL CHECK (json_valid(payload_json)),
  status                TEXT NOT NULL DEFAULT 'received' CHECK (status IN (
                          'received', 'validating', 'imported', 'failed', 'rejected'
                        )),
  source_id             TEXT REFERENCES sources(id) ON DELETE SET NULL,
  error_code            TEXT,
  error_message         TEXT,
  received_at           INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  completed_at          INTEGER,
  UNIQUE (extension_id, external_request_id)
) STRICT;

CREATE INDEX capture_requests_status_idx ON capture_requests(status, received_at);

CREATE TABLE usage_events (
  id                    TEXT PRIMARY KEY,
  session_id            TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  provider_profile_id   TEXT REFERENCES provider_profiles(id) ON DELETE SET NULL,
  provider              TEXT NOT NULL CHECK (provider IN ('openai', 'anthropic', 'openrouter')),
  model_id              TEXT NOT NULL,
  operation             TEXT NOT NULL CHECK (operation IN (
                          'generate', 'stream', 'probe_evaluation', 'source_card',
                          'web_search', 'transcription', 'vision', 'rerank', 'other'
                        )),
  provider_request_id   TEXT,
  input_tokens          INTEGER CHECK (input_tokens IS NULL OR input_tokens >= 0),
  cached_input_tokens   INTEGER CHECK (cached_input_tokens IS NULL OR cached_input_tokens >= 0),
  output_tokens         INTEGER CHECK (output_tokens IS NULL OR output_tokens >= 0),
  reasoning_tokens      INTEGER CHECK (reasoning_tokens IS NULL OR reasoning_tokens >= 0),
  estimated_cost_microusd INTEGER CHECK (estimated_cost_microusd IS NULL OR estimated_cost_microusd >= 0),
  latency_ms            INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
  success               INTEGER NOT NULL CHECK (success IN (0, 1)),
  error_code            TEXT,
  metadata_json         TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata_json)),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))
) STRICT;

CREATE INDEX usage_events_time_idx ON usage_events(created_at DESC);
CREATE INDEX usage_events_session_idx ON usage_events(session_id, created_at);
CREATE INDEX usage_events_provider_idx ON usage_events(provider_profile_id, model_id, created_at);

CREATE TABLE usage_limits (
  id                    TEXT PRIMARY KEY,
  scope_type            TEXT NOT NULL CHECK (scope_type IN ('global', 'studio', 'provider_profile')),
  scope_id              TEXT NOT NULL,
  period                TEXT NOT NULL CHECK (period IN ('session', 'day', 'month')),
  warning_microusd      INTEGER CHECK (warning_microusd IS NULL OR warning_microusd >= 0),
  hard_limit_microusd   INTEGER CHECK (hard_limit_microusd IS NULL OR hard_limit_microusd >= 0),
  enabled               INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  updated_at            INTEGER NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),
  UNIQUE (scope_type, scope_id, period),
  CHECK (
    hard_limit_microusd IS NULL OR warning_microusd IS NULL OR
    warning_microusd <= hard_limit_microusd
  )
) STRICT;

-- -----------------------------------------------------------------------------
-- Cross-table invariants that SQLite cannot express as ordinary CHECK constraints
-- -----------------------------------------------------------------------------

CREATE TRIGGER session_source_version_same_source_insert
BEFORE INSERT ON session_sources
FOR EACH ROW
WHEN NEW.source_version_id IS NOT NULL
 AND (SELECT source_id FROM source_versions WHERE id = NEW.source_version_id) IS NOT NEW.source_id
BEGIN
  SELECT RAISE(ABORT, 'session source version must belong to source');
END;

CREATE TRIGGER annotation_version_same_source_insert
BEFORE INSERT ON annotations
FOR EACH ROW
WHEN NEW.source_version_id IS NOT NULL
 AND (SELECT source_id FROM source_versions WHERE id = NEW.source_version_id) IS NOT NEW.source_id
BEGIN
  SELECT RAISE(ABORT, 'annotation source version must belong to source');
END;

CREATE TRIGGER annotation_block_same_version_insert
BEFORE INSERT ON annotations
FOR EACH ROW
WHEN NEW.source_block_id IS NOT NULL
 AND (SELECT sv.source_id
      FROM source_blocks sb
      JOIN source_versions sv ON sv.id = sb.source_version_id
      WHERE sb.id = NEW.source_block_id) IS NOT NEW.source_id
BEGIN
  SELECT RAISE(ABORT, 'annotation block must belong to source');
END;

CREATE TRIGGER session_source_version_same_source_update
BEFORE UPDATE OF source_id, source_version_id ON session_sources
FOR EACH ROW
WHEN NEW.source_version_id IS NOT NULL
 AND (SELECT source_id FROM source_versions WHERE id = NEW.source_version_id) IS NOT NEW.source_id
BEGIN
  SELECT RAISE(ABORT, 'session source version must belong to source');
END;

CREATE TRIGGER annotation_version_same_source_update
BEFORE UPDATE OF source_id, source_version_id ON annotations
FOR EACH ROW
WHEN NEW.source_version_id IS NOT NULL
 AND (SELECT source_id FROM source_versions WHERE id = NEW.source_version_id) IS NOT NEW.source_id
BEGIN
  SELECT RAISE(ABORT, 'annotation source version must belong to source');
END;

CREATE TRIGGER annotation_block_same_source_update
BEFORE UPDATE OF source_id, source_block_id ON annotations
FOR EACH ROW
WHEN NEW.source_block_id IS NOT NULL
 AND (SELECT sv.source_id
      FROM source_blocks sb
      JOIN source_versions sv ON sv.id = sb.source_version_id
      WHERE sb.id = NEW.source_block_id) IS NOT NEW.source_id
BEGIN
  SELECT RAISE(ABORT, 'annotation block must belong to source');
END;

CREATE TRIGGER probe_session_scope_insert
BEFORE INSERT ON probes
FOR EACH ROW
WHEN (SELECT mode FROM sessions WHERE id = NEW.session_id) IS NOT 'probe'
  OR (SELECT studio_id FROM sessions WHERE id = NEW.session_id) IS NOT NEW.studio_id
BEGIN
  SELECT RAISE(ABORT, 'probe session must be probe mode and use the same Studio');
END;

COMMIT;
